/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,ts,css,scss}"
  ],
  theme: {
    extend: {
      colors: {
        'pitch-black': 'var(--color-pitch-black)',
        'graphite': 'var(--color-graphite)',
        'deep-slate': 'var(--color-deep-slate)',
        'charcoal-grey': 'var(--color-charcoal-grey)',
        'muted-ash': 'var(--color-muted-ash)',
        'gunmetal': 'var(--color-gunmetal)',
        'porcelain': 'var(--color-porcelain)',
        'light-steel': 'var(--color-light-steel)',
        'storm-cloud': 'var(--color-storm-cloud)',
        'fog-grey': 'var(--color-fog-grey)',
        'alabaster': 'var(--color-alabaster)',
        'neon-lime': 'var(--color-neon-lime)',
        'aether-blue': 'var(--color-aether-blue)',
        'forest-green': 'var(--color-forest-green)',
        'cyan-spark': 'var(--color-cyan-spark)',
        'emerald': 'var(--color-emerald)',
        'warning-red': 'var(--color-warning-red)',
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scaleIn 0.2s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-down-fade': 'slideDownFade 0.2s ease-out',
        'slide-up-fade': 'slideUpFade 0.2s ease-out',
        'float-fast': 'float 4s ease-in-out infinite 2s',
        'marquee': 'marquee 35s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(10px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        scaleIn: { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(20px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        slideDownFade: { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUpFade: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-10px)' } },
        marquee: { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-50%)' } },
      },
    },
  },
  plugins: [],
}